version: 2
updates:
- package-ecosystem: cargo
  directory: "/crawler"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: reqwest
    versions:
    - 0.11.0
    - 0.11.1
    - 0.11.2
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: geojson
    versions:
    - 0.21.0
    - 0.22.0
